services:
  mysql:
    image: mysql
    restart: always
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ccd
      MYSQL_USER: ccd
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  postgres:
    image: postgres
    restart: always
    platform: linux/amd64
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ccd
      POSTGRES_USER: ccd
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  mysql_volume:
  postgres_volume:
